language: python
python:
    - "3.6.1"
install:
    - "pip install -r requirements.txt"
    - "pip install coverage"
    - "pip install coveralls"
script: nosetests --with-coverage

after_success:
    - coveralls
