"""empty message

Revision ID: fd748cffbbb1
Revises: 9890aeffa818
Create Date: 2017-07-06 21:51:43.894083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd748cffbbb1'
down_revision = '9890aeffa818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('buckets_name_key', 'buckets', type_='unique')
    op.drop_constraint('items_name_key', 'items', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('items_name_key', 'items', ['name'])
    op.create_unique_constraint('buckets_name_key', 'buckets', ['name'])
    # ### end Alembic commands ###
